version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/craft-rest-api-master"
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: "/nft-cw"
    schedule:
      interval: daily