MongoDB:
  host: 127.0.0.1
  port: 27017
  database: "databasehere"
  username: "user"
  password: "password"
Redis:
  host: "localhost"
  port: 6379
  username: ""
  password: ""
API_ENDPOINT: "http://localhost:1317/cosmos/bank/v1beta1"
TOKEN_FAUCET_ENDPOINT: "http://0.0.0.0:4500/"
SERVER_WALLET_ADDRESS: "craft10r39fueph9fq7a6lgswu4zdsg8t3gxlqd6lnf0"