MongoDB:
  host: 127.0.0.1
  port: 27017
  database: "crafteconomy"
  username: "user"
  password: "password"
Redis:
  host: "localhost"
  port: 6379
  password: ""
TAX_RATE: 0.05
API_ENDPOINT: http://65.108.125.182:1317/
SERVER_WALLET_ADDRESS: craft10r39fueph9fq7a6lgswu4zdsg8t3gxlqd6lnf0
SIGNING_WEBAPP_LINK: http://65.108.71.66:8081/